index: 1
description: Quiero saber las cosas básicas que puedo hacer para aumentar la seguridad
  de mi correo electrónico. Necesito saber qué hacer si creo que mi correo ha sido
  hackeado.
title: Principiante
